### ISSUE TITLE
signing inner_path

### ISSUE THREAD

**Issue by kustomzone** [Fazelesswhite/ZeroMail-2.0#1]
Hi FaZe, guessing you might still need to sign inner path of data/users/content.json as per tutorial part2.

`zeronet.py siteSign [siteaddress] --inner_path data/users/content.json`

(clone site works, but _data/users/content.json_ is missing in the original)

**Comment by Fazelesswhite** [comment]
I've fixed in the latest commit thanks for pointing out @kustomzone :D
